// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/1talent/gotraining/internal/types/operations/auth"
)

// NewAllaboutappsDevAwGoStarterAPI creates a new AllaboutappsDevAwGoStarter instance
func NewAllaboutappsDevAwGoStarterAPI(spec *loads.Document) *AllaboutappsDevAwGoStarterAPI {
	return &AllaboutappsDevAwGoStarterAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer: runtime.JSONConsumer(),

		JSONProducer: runtime.JSONProducer(),

		AuthGetUserInfoRouteHandler: auth.GetUserInfoRouteHandlerFunc(func(params auth.GetUserInfoRouteParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation auth.GetUserInfoRoute has not yet been implemented")
		}),
		AuthPostChangePasswordRouteHandler: auth.PostChangePasswordRouteHandlerFunc(func(params auth.PostChangePasswordRouteParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation auth.PostChangePasswordRoute has not yet been implemented")
		}),
		AuthPostForgotPasswordCompleteRouteHandler: auth.PostForgotPasswordCompleteRouteHandlerFunc(func(params auth.PostForgotPasswordCompleteRouteParams) middleware.Responder {
			return middleware.NotImplemented("operation auth.PostForgotPasswordCompleteRoute has not yet been implemented")
		}),
		AuthPostForgotPasswordRouteHandler: auth.PostForgotPasswordRouteHandlerFunc(func(params auth.PostForgotPasswordRouteParams) middleware.Responder {
			return middleware.NotImplemented("operation auth.PostForgotPasswordRoute has not yet been implemented")
		}),
		AuthPostLoginRouteHandler: auth.PostLoginRouteHandlerFunc(func(params auth.PostLoginRouteParams) middleware.Responder {
			return middleware.NotImplemented("operation auth.PostLoginRoute has not yet been implemented")
		}),
		AuthPostLogoutRouteHandler: auth.PostLogoutRouteHandlerFunc(func(params auth.PostLogoutRouteParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation auth.PostLogoutRoute has not yet been implemented")
		}),
		AuthPostRefreshRouteHandler: auth.PostRefreshRouteHandlerFunc(func(params auth.PostRefreshRouteParams) middleware.Responder {
			return middleware.NotImplemented("operation auth.PostRefreshRoute has not yet been implemented")
		}),
		AuthPostRegisterRouteHandler: auth.PostRegisterRouteHandlerFunc(func(params auth.PostRegisterRouteParams) middleware.Responder {
			return middleware.NotImplemented("operation auth.PostRegisterRoute has not yet been implemented")
		}),

		// Applies when the "Authorization" header is set
		BearerAuth: func(token string) (interface{}, error) {
			return nil, errors.NotImplemented("api key auth (Bearer) Authorization from header param [Authorization] has not yet been implemented")
		},
		// default authorizer is authorized meaning no requests are blocked
		APIAuthorizer: security.Authorized(),
	}
}

/*AllaboutappsDevAwGoStarterAPI API documentation */
type AllaboutappsDevAwGoStarterAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// BearerAuth registers a function that takes a token and returns a principal
	// it performs authentication based on an api key Authorization provided in the header
	BearerAuth func(string) (interface{}, error)

	// APIAuthorizer provides access control (ACL/RBAC/ABAC) by providing access to the request and authenticated principal
	APIAuthorizer runtime.Authorizer

	// AuthGetUserInfoRouteHandler sets the operation handler for the get user info route operation
	AuthGetUserInfoRouteHandler auth.GetUserInfoRouteHandler
	// AuthPostChangePasswordRouteHandler sets the operation handler for the post change password route operation
	AuthPostChangePasswordRouteHandler auth.PostChangePasswordRouteHandler
	// AuthPostForgotPasswordCompleteRouteHandler sets the operation handler for the post forgot password complete route operation
	AuthPostForgotPasswordCompleteRouteHandler auth.PostForgotPasswordCompleteRouteHandler
	// AuthPostForgotPasswordRouteHandler sets the operation handler for the post forgot password route operation
	AuthPostForgotPasswordRouteHandler auth.PostForgotPasswordRouteHandler
	// AuthPostLoginRouteHandler sets the operation handler for the post login route operation
	AuthPostLoginRouteHandler auth.PostLoginRouteHandler
	// AuthPostLogoutRouteHandler sets the operation handler for the post logout route operation
	AuthPostLogoutRouteHandler auth.PostLogoutRouteHandler
	// AuthPostRefreshRouteHandler sets the operation handler for the post refresh route operation
	AuthPostRefreshRouteHandler auth.PostRefreshRouteHandler
	// AuthPostRegisterRouteHandler sets the operation handler for the post register route operation
	AuthPostRegisterRouteHandler auth.PostRegisterRouteHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// UseRedoc for documentation at /docs
func (o *AllaboutappsDevAwGoStarterAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *AllaboutappsDevAwGoStarterAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *AllaboutappsDevAwGoStarterAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *AllaboutappsDevAwGoStarterAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *AllaboutappsDevAwGoStarterAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *AllaboutappsDevAwGoStarterAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *AllaboutappsDevAwGoStarterAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *AllaboutappsDevAwGoStarterAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *AllaboutappsDevAwGoStarterAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the AllaboutappsDevAwGoStarterAPI
func (o *AllaboutappsDevAwGoStarterAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.BearerAuth == nil {
		unregistered = append(unregistered, "AuthorizationAuth")
	}

	if o.AuthGetUserInfoRouteHandler == nil {
		unregistered = append(unregistered, "auth.GetUserInfoRouteHandler")
	}
	if o.AuthPostChangePasswordRouteHandler == nil {
		unregistered = append(unregistered, "auth.PostChangePasswordRouteHandler")
	}
	if o.AuthPostForgotPasswordCompleteRouteHandler == nil {
		unregistered = append(unregistered, "auth.PostForgotPasswordCompleteRouteHandler")
	}
	if o.AuthPostForgotPasswordRouteHandler == nil {
		unregistered = append(unregistered, "auth.PostForgotPasswordRouteHandler")
	}
	if o.AuthPostLoginRouteHandler == nil {
		unregistered = append(unregistered, "auth.PostLoginRouteHandler")
	}
	if o.AuthPostLogoutRouteHandler == nil {
		unregistered = append(unregistered, "auth.PostLogoutRouteHandler")
	}
	if o.AuthPostRefreshRouteHandler == nil {
		unregistered = append(unregistered, "auth.PostRefreshRouteHandler")
	}
	if o.AuthPostRegisterRouteHandler == nil {
		unregistered = append(unregistered, "auth.PostRegisterRouteHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *AllaboutappsDevAwGoStarterAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *AllaboutappsDevAwGoStarterAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	result := make(map[string]runtime.Authenticator)
	for name := range schemes {
		switch name {
		case "Bearer":
			scheme := schemes[name]
			result[name] = o.APIKeyAuthenticator(scheme.Name, scheme.In, o.BearerAuth)

		}
	}
	return result
}

// Authorizer returns the registered authorizer
func (o *AllaboutappsDevAwGoStarterAPI) Authorizer() runtime.Authorizer {
	return o.APIAuthorizer
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *AllaboutappsDevAwGoStarterAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *AllaboutappsDevAwGoStarterAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *AllaboutappsDevAwGoStarterAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the allaboutapps dev aw go starter API
func (o *AllaboutappsDevAwGoStarterAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *AllaboutappsDevAwGoStarterAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/api/v1/auth/userinfo"] = auth.NewGetUserInfoRoute(o.context, o.AuthGetUserInfoRouteHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/api/v1/auth/change-password"] = auth.NewPostChangePasswordRoute(o.context, o.AuthPostChangePasswordRouteHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/api/v1/auth/forgot-password/complete"] = auth.NewPostForgotPasswordCompleteRoute(o.context, o.AuthPostForgotPasswordCompleteRouteHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/api/v1/auth/forgot-password"] = auth.NewPostForgotPasswordRoute(o.context, o.AuthPostForgotPasswordRouteHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/api/v1/auth/login"] = auth.NewPostLoginRoute(o.context, o.AuthPostLoginRouteHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/api/v1/auth/logout"] = auth.NewPostLogoutRoute(o.context, o.AuthPostLogoutRouteHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/api/v1/auth/refresh"] = auth.NewPostRefreshRoute(o.context, o.AuthPostRefreshRouteHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/api/v1/auth/register"] = auth.NewPostRegisterRoute(o.context, o.AuthPostRegisterRouteHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *AllaboutappsDevAwGoStarterAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *AllaboutappsDevAwGoStarterAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *AllaboutappsDevAwGoStarterAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *AllaboutappsDevAwGoStarterAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *AllaboutappsDevAwGoStarterAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[method][path] = builder(h)
	}
}
