// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostRegisterPayLoad post register pay load
//
// swagger:model PostRegisterPayLoad
type PostRegisterPayLoad struct {

	// Password to register with
	// Example: correcthorsebatterystaple
	// Required: true
	// Max Length: 500
	// Min Length: 1
	Password *string `json:"password"`

	// Username to register with
	// Required: true
	// Max Length: 255
	// Format: email
	Username *strfmt.Email `json:"username"`
}

// Validate validates this post register pay load
func (m *PostRegisterPayLoad) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePassword(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUsername(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostRegisterPayLoad) validatePassword(formats strfmt.Registry) error {

	if err := validate.Required("password", "body", m.Password); err != nil {
		return err
	}

	if err := validate.MinLength("password", "body", *m.Password, 1); err != nil {
		return err
	}

	if err := validate.MaxLength("password", "body", *m.Password, 500); err != nil {
		return err
	}

	return nil
}

func (m *PostRegisterPayLoad) validateUsername(formats strfmt.Registry) error {

	if err := validate.Required("username", "body", m.Username); err != nil {
		return err
	}

	if err := validate.MaxLength("username", "body", m.Username.String(), 255); err != nil {
		return err
	}

	if err := validate.FormatOf("username", "body", "email", m.Username.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post register pay load based on context it is used
func (m *PostRegisterPayLoad) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostRegisterPayLoad) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostRegisterPayLoad) UnmarshalBinary(b []byte) error {
	var res PostRegisterPayLoad
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
