# Uses PG* env vars
# the live database
development:
    dialect: postgres
    datasource: host=localhost dbname=development user=dbuser password=dbpass port=5432 sslmode=disable
    dir: migrations
    table: migrations

# Uses PSQL_* env vars
# the spec database (used for introspection purposes e.g. generate the sqlboiler models)
spec:
    dialect: postgres
    datasource: host=localhost dbname=development user=dbuser password=dbpass port=5432 sslmode=disable
    dir: migrations
    table: migrations