SHELL := /bin/zsh

### -----------------------
# --- Swagger
### -----------------------

swagger: ##- Runs make swagger-concat, swagger-lint-ref-siblings, and swagger-server.
	@$(MAKE) swagger-concat
	@$(MAKE) swagger-lint-ref-siblings
	@$(MAKE) swagger-server

# Any sibling elements of a $ref are ignored. This is because $ref works by replacing itself and everything on its level with the definition it is pointing at.
# https://swagger.io/docs/specification/using-ref/
swagger-lint-ref-siblings: ##- (opt) Checks api/**/*.[yml|yaml] for invalid usage of $ref (no siblings).
	@echo "make swagger-lint-ref-siblings"
	@rm -f /tmp/swagger-lint-ref-siblings-errors.log && touch /tmp/swagger-lint-ref-siblings-errors.log
	@find api -type f -name "*.yml" -o -name "*.yaml" \
		| { \
			while read ymlfile; \
			do \
				ref_siblings=$$(yq e '.. | select(has("$$ref") and length != 1)' $$ymlfile); \
				([[ -z "$$ref_siblings" ]] \
					|| (echo "Error: Found invalid \$$ref siblings within $$ymlfile:" \
						&& (yq -P e '[.. | select(has("$$ref") and length != 1)]' $$ymlfile) \
						&& (echo $$ymlfile >> /tmp/swagger-lint-ref-siblings-errors.log))); \
			done \
		};
	@[[ "$$(cat /tmp/swagger-lint-ref-siblings-errors.log | wc -l)" -eq "0" ]] \
		|| (echo "Error: $$(cat /tmp/swagger-lint-ref-siblings-errors.log | wc -l) files have \$$ref(s) with siblings!" \
			&& false)

# https://goswagger.io/usage/mixin.html
# https://goswagger.io/usage/flatten.html
swagger-concat: ##- (opt) Regenerates api/swagger.yml based on api/paths/*.
	@echo "make swagger-concat"
	@rm -rf api/tmp
	@mkdir -p api/tmp
	@swagger mixin \
		--output=api/tmp/tmp.yml \
		--format=yaml \
		--keep-spec-order \
		api/config/main.yml api/paths/* \
		-q
	@swagger flatten api/tmp/tmp.yml \
		--output=api/swagger.yml \
		--format=yaml \
		-q
# @sed -i '1s@^@# // Code generated by "make swagger"; DO NOT EDIT.\n@' api/swagger.yml

# https://goswagger.io/generate/server.html
# Note that we first flag all files to delete (as previously generated), regenerate, then delete all still flagged files
# This allows us to ensure that any filewatchers (VScode) don't panic as these files are removed.
# --keep-spec-order is broken (/tmp spec resolving): https://github.com/go-swagger/go-swagger/issues/2216
swagger-server: ##- (opt) Regenerates internal/types based on api/swagger.yml.
	@echo "make swagger-server"
# @grep -R -L '^// Code generated .* DO NOT EDIT\.$$$$' ./internal/types \
# 	| xargs sed -i '1s#^#// DELETE ME; DO NOT EDIT.\n#'
	@swagger generate server \
		--allow-template-override \
		--template-dir=api/templates \
		--spec=api/swagger.yml \
		--server-package=internal/types \
		--model-package=internal/types \
		--exclude-main \
		--config-file=api/config/go-swagger-config.yml \
		-q
	@find internal/types -type f -exec grep -q '^// DELETE ME; DO NOT EDIT\.$$' {} \; -delete

watch-swagger: ##- Watches *.yml|yaml|gotmpl files in /api and runs 'make swagger' on modifications.
	@echo "Watching /api/**/*.yml|yaml|gotmpl. Use Ctrl-c to stop a run or exit."
	watchexec -p -w api -i tmp -i api/swagger.yml --exts yml,yaml,gotmpl $(MAKE) swagger