swagger: "2.0"
info:
  title: github.com/1talent/gotraining
  version: 0.1.0
paths: {}
definitions:
  User:
    type: object
    required:
      - id
    properties:
      id:
        type: string
        format: uuid4
        description: ID of User
        example: 891d37d3-c74f-493e-aea8-af73efd92016
  PostRegisterPayLoad:
    type: object
    required:
      - username
      - password
    properties:
      password:
        description: Password to register with
        type: string
        maxLength: 500
        minLength: 1
        example: correcthorsebatterystaple
      username:
        description: Username to register with
        type: string
        format: email
        maxLength: 255